export { default as BookingsTab } from './BookingsTab'
export { default as WishlistTab } from './WishlistTab'
export { default as SettingsTab } from './SettingsTab'
export { default as InboxTab } from './InboxTab'
export { default as NotificationsTab } from './NotificationsTab'
